logging:
  level:
    root: INFO
    edo_service: DEBUG
    edo_service.service: DEBUG
  file:
    name: logs/edo-service.log
    append: true
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger] - %msg%n"  # ✅ Логгер теперь будет отображать твои классы!
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger] - %msg%n"


  spring:
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        group-id: edo-consumer-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              trusted:
                packages: "*"

  kafka:
    topic:
      approval-events: approval-events
      additional-approval-events: additional-approval-events