logging:
  level:
    root: INFO
    edo_repository.repository: DEBUG
  file:
    path: logs/
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"


spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

